apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: what2cook
type: Opaque
stringData:
  DB_USER: "what2cook"
  DB_PASSWORD: ""          # tofu output postgres_password
  SPOONACULAR_KEY: ""
  SPOONACULAR_KEY_2: ""
  SPOONACULAR_KEY_BACKGROUND: ""
  OPENAI_API_KEY: ""
  GEMINI_API_KEY: ""
